name: Build packages

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types:
      - opened
      - synchronize
      - reopened

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        build_type: [debug, release]
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3
      - name: Build ${{ matrix.os }}-${{ matrix.build_type }}
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} ..
          cmake --build . --config ${{ matrix.build_type }} -j
      - name: Pack (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          tar -czvf gkernel-${{ matrix.os }}-${{ matrix.build_type }}.tar.gz build/bin_${{ matrix.build_type }}
      - name: Pack (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          Compress-Archive -Path build\bin_${{ matrix.build_type }} -DestinationPath gkernel-${{ matrix.os }}-${{ matrix.build_type }}.zip
      - name: Save package
        uses: actions/upload-artifact@v3
        with:
          name: gkernel-${{ matrix.os }}-${{ matrix.build_type }}
          path: gkernel-${{ matrix.os }}-${{ matrix.build_type }}.*
